version: '3.7'
services:

  http-proxy:
    image: simbam1/http-proxy:1.0
    container_name: http-proxy
    build: 
      context: './gtas-parent/docker-resources'
      dockerfile: 'proxy.Dockerfile'
    restart: always
    secrets:
      - elastic_bootstrap_password
    ports:
      - 80:80
    networks:
      - GTAS_webapp-network
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-node

  web-app:
    image: simbam1/web-app:1.0
    container_name: web-app
    build: './gtas-parent'
    ports:
      - 8080:8080
    environment: 
      - DB_HOST=mariadb
      - KIBANA_HOST=kibana
      - NEO4J_HOST=neo4j
      - ACTIVEMQ_HOST=activemq
      - PROXY_HOST=httpproxy
      - ELASTICSEARCH=elasticsearch
    networks:
      - GTAS_webapp-network
    restart: always
    secrets:
     - mysql_webapp_user
     - mysql_webapp_password
     - webapp_neo4j_user
     - webapp_neo4j_password
     - elastic_bootstrap_password
     - source: elastic_key
       target: /usr/local/tomcat/conf/elasticsearch-node1.key
     - source: elastic_ca
       target: /usr/local/tomcat/conf/elastic-ca.crt
     - source: elastic_cert
       target: /usr/local/tomcat/conf/elasticsearch-node1.crt
    volumes:
      - m2:/root/.m2
      - scheduler-logs:/scheduler-logs
    depends_on: 
      - mariadb
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-node

  gtas-scheduler:
    image: simbam1/gtas-scheduler:1.0
    container_name: gtas-scheduler
    build:
      context: .
      dockerfile: gtas-parent/gtas-job-scheduler-war/Dockerfile
    restart: always    
    environment:
      DB_HOST: mariadb
      KIBANA_HOST: kibana
      NEO4J_HOST: neo4j
      ACTIVEMQ_HOST: activemq
    volumes:
      - scheduler-logs:/usr/local/tomcat/logs
      - type: bind
        source: ./gtas-data
        target: /usr/local/gtas-data
        consistency: consistent
    secrets:
      - mysql_processor_user
      - mysql_processor_password
      - webapp_neo4j_user
      - webapp_neo4j_password
    networks:
      - GTAS_webapp-network
    depends_on: 
      - activemq
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-node

  activemq:
    image: rmohr/activemq
    container_name: activemq
    restart: always
    networks: 
      - GTAS_webapp-network
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-node

  mariadb:
    image: simbam1/mariadb:1.0
    build:
      context: './gtas-parent'
      dockerfile: 'Dockerfile-mariadb'
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
     - mysql_etl_user
     - mysql_etl_password
     - mysql_processor_user
     - mysql_processor_password
     - mysql_webapp_user
     - mysql_webapp_password
     - mysql_healthcheck_user
     - mysql_healthcheck_password
     - mysql_logstash_user
     - mysql_logstash_password
     - mysql_root_password
    ports:
      - 3306:3306
    networks:
      - GTAS_webapp-network
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-node


secrets:
  mysql_etl_user:
    file: ./gtas-parent/gtas-commons/secrets/mysql_etl_user.txt
  mysql_etl_password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_etl_password.txt
  mysql_healthcheck_user:
    file: ./gtas-parent/gtas-commons/secrets/mysql_healthcheck_user.txt
  mysql_healthcheck_password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_healthcheck_password.txt
  mysql_logstash_user:
    file: ./gtas-parent/gtas-commons/secrets/mysql_logstash_user.txt
  mysql_logstash_password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_logstash_password.txt
  elastic_bootstrap_password:
    file: ./gtas-parent/gtas-commons/secrets/elastic_bootstrap_password.txt
  mysql_processor_user:
    file: ./gtas-parent/gtas-commons/secrets/mysql_processor_user.txt
  mysql_processor_password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_processor_password.txt
  mysql_webapp_user:
    file: ./gtas-parent/gtas-commons/secrets/mysql_webapp_user.txt
  mysql_webapp_password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_webapp_password.txt
  mysql_root_password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_root_password.txt
  webapp_neo4j_user:
    file: ./gtas-parent/gtas-commons/secrets/webapp_neo4j_user.txt
  webapp_neo4j_password:
    file: ./gtas-parent/gtas-commons/secrets/webapp_neo4j_password.txt
  elastic_key:
    file: ./gtas-parent/gtas-commons/secrets/elasticsearch-node1.key
  elastic_ca:
    file: ./gtas-parent/gtas-commons/secrets/elastic-ca.crt
  elastic_cert:
    file: ./gtas-parent/gtas-commons/secrets/elasticsearch-node1.crt

volumes:
  db-data:
  m2:
  scheduler-logs:

networks:
  GTAS_webapp-network:
    driver: "overlay"
    attachable: true