version: '3.7'
services:
  web-app:
    environment:
      PROXY_IP: localhost
  gtas-scheduler:
    volumes:
      - type: bind
        source: ./gtas-data
        target: /usr/local/gtas-data
        consistency: consistent