version: "3.7"

services:

  etl-job:
    container_name: etl-job
    build:
      context: .
      dockerfile: ./gtas-neo4j-etl/etl_job.Dockerfile
    environment:
      NEO4J_HOSTNAME: neo4j
      DB_HOSTNAME: mariadb
    image: neo4j-etl-job
    restart: always
    secrets:
      - mysql_etl_user
      - mysql_etl_password
      - etl_neo4j_user
      - etl_neo4j_password
    networks: 
      - GTAS_webapp-network
    depends_on: 
      - neo4j

  neo4j:
    container_name: neo4j
    build:
      context: .
      dockerfile: ./gtas-neo4j-etl/neo4j.Dockerfile
    image: gtas-neo4j
    restart: always
    ports:
      - 7474:7474   
      - 7687:7687
    networks: 
      - GTAS_webapp-network


networks:
  GTAS_webapp-network:
    driver: "bridge"

secrets:
  mysql_etl_user:
    file: ./gtas-parent/gtas-commons/secrets/mysql_etl_user.txt
  mysql_etl_password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_etl_password.txt
  etl_neo4j_user:
    file: ./gtas-parent/gtas-commons/secrets/etl_neo4j_user.txt
  etl_neo4j_password:
    file: ./gtas-parent/gtas-commons/secrets/etl_neo4j_password.txt