version: '3.7'
services:
  http-proxy:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-app-node
  gtas-scheduler:
    volumes:
      - type: bind
        source: /mnt
        target: /usr/local/gtas-data
        consistency: consistent
  web-app:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-app-node
  gtas-scheduler:    
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-app-node
  activemq:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-db-node
  mariadb:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-db-node
  kibana:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-elk-node
  elasticsearch:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-elk-node
  logstash:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-elk-node
  elk-setup:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-elk-node
  elt-job:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-app-node
  neo4j:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-app-node

networks:
  GTAS_webapp-network:
    driver: "overlay"
    attachable: true